openapi: 3.1.0
info:
  title: product.v1
paths:
  /v1/products/{product_id}:
    get:
      tags:
        - product.v1.ProductService
      summary: GetProduct
      description: 1. Standard gRPC definition
      operationId: product.v1.ProductService.GetProduct
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
            title: product_id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product.v1.Product'
components:
  schemas:
    product.v1.GetProductRequest:
      type: object
      properties:
        productId:
          type: string
          title: product_id
      title: GetProductRequest
      additionalProperties: false
    product.v1.Product:
      type: object
      properties:
        id:
          type: string
          title: id
        name:
          type: string
          title: name
        price:
          type: number
          title: price
          format: double
      title: Product
      additionalProperties: false
security: []
tags:
  - name: product.v1.ProductService
